use domain::ledger::{Project, Voucher, VoucherItem, VoucherStatus};
use domain::repositories::{ProjectRepository, VoucherRepository};
use anyhow::Result;
use chrono::Utc;

pub struct ProjectService {
    project_repo: Box<dyn ProjectRepository>,
    voucher_repo: Box<dyn VoucherRepository>,
}

impl ProjectService {
    pub fn new(project_repo: Box<dyn ProjectRepository>, voucher_repo: Box<dyn VoucherRepository>) -> Self {
        Self { project_repo, voucher_repo }
    }

    pub async fn record_income_expense(
        &self, 
        project_id: i64, 
        amount: f64, 
        is_income: bool, 
        account_id: i64,
        description: String
    ) -> Result<i64> {
        // In a real accounting system, we'd determine the offsetting account based on the type.
        // For this prototype, we assume a simple Cash account (ID: 1) for the other side of the entry.
        let cash_account_id = 1; 
        
        let (debit_acc, credit_acc) = if is_income {
            (cash_account_id, account_id)
        } else {
            (account_id, cash_account_id)
        };

        let voucher = Voucher {
            id: 0, // Generated by DB
            voucher_date: Utc::now().date_naive(),
            description: Some(description),
            project_id: Some(project_id),
            status: VoucherStatus::Unposted,
            items: vec![],
        };

        let items = vec![
            VoucherItem {
                id: 0,
                voucher_id: 0,
                account_id: debit_acc,
                debit: amount,
                credit: 0.0,
                description: None,
            },
            VoucherItem {
                id: 0,
                voucher_id: 0,
                account_id: credit_acc,
                debit: 0.0,
                credit: amount,
                description: None,
            },
        ];

        // Logic check: must be balanced
        // Note: we create a temporary voucher object to check balance since our struct requires items
        let mut balance_check_voucher = voucher.clone();
        balance_check_voucher.items = items.clone();
        if !balance_check_voucher.is_balanced() {
            return Err(anyhow::anyhow!("Voucher is not balanced"));
        }

        self.voucher_repo.create_voucher(&voucher, &items).await
    }
}
